controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# config/routes.yaml

app_homepage:
    path: /
    controller: App\Controller\DashboardController::index

dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index